name: Run test suite

on:
  push:
    branches:
    - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: Install arkworks-bridge
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with:
        repo: l-adic/arkworks-bridge
        tag: v1.0.0-rc2


    - name: Run arkworks-bridge
      run: |
        arkworks-bridge create-trusted-setup --r1cs ./proof-data/sudoku-r1cs.jsonl --proving-key ./proof-data/sudoku-pk --verifying-key ./proof-data/sudoku-vk --ethereum
        arkworks-bridge generate-contract --contract ./contracts/Verifier.sol --verifying-key ./proof-data/sudoku-vk --inputs ./proof-data/sudoku-assignments.jsonl
        arkworks-bridge create-proof --proof ./proof-data/sudoku-proof --proving-key ./proof-data/sudoku-pk --r1cs ./proof-data/sudoku-r1cs.jsonl --witness ./proof-data/sudoku-witness.jsonl --ethereum

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc

    - name: Run tests against cliquebait
      run: |
        docker run -d -p 8545:8545 -e ACCOUNTS_TO_CREATE=10 foamspace/cliquebait:v1.12.0
        sleep 10
        npm install
        npm run chanterelle-build
        npm run test
